version: '3.8'

services:
  statsbot:
    build:
      context: .
      dockerfile: ./cmd/statsbot/Dockerfile
    image: go-statsbot:latest
    container_name: statsbot
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: statsbot-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
